
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "farePortType", targetNamespace = "tns:fare")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FarePortType {


    /**
     * Send a greeting message. For testing purposes.
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "tns:fare#sayhello")
    @WebResult(name = "greeting", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "tns:fare", className = "client.SayHelloRequestType")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "tns:fare", className = "client.SayHelloResponseType")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * Retrieve a list of train stations for the San Francisco BART.
     * 
     * @param parameters
     * @return
     *     returns client.GetStationsResponseType
     */
    @WebMethod(action = "tns:fare#getStations")
    @WebResult(name = "getStationsResponse", targetNamespace = "tns:fare", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetStationsResponseType getStations(
        @WebParam(name = "getStations", targetNamespace = "tns:fare", partName = "parameters")
        GetStationsRequestType parameters);

    /**
     * Retrieve a train fare for travel between two stations on the San Francisco BART.
     * 
     * @param parameters
     * @return
     *     returns client.GetFareResponseType
     */
    @WebMethod(action = "tns:fare#getFare")
    @WebResult(name = "getFareResponse", targetNamespace = "tns:fare", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetFareResponseType getFare(
        @WebParam(name = "getFare", targetNamespace = "tns:fare", partName = "parameters")
        GetFareRequestType parameters);

}
