
package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "fare", targetNamespace = "tns:fare", wsdlLocation = "http://www-student.it.uts.edu.au/~brookes/bart/fare.wsdl")
public class Fare
    extends Service
{

    private final static URL FARE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.Fare.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.Fare.class.getResource(".");
            url = new URL(baseUrl, "http://www-student.it.uts.edu.au/~brookes/bart/fare.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www-student.it.uts.edu.au/~brookes/bart/fare.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FARE_WSDL_LOCATION = url;
    }

    public Fare(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Fare() {
        super(FARE_WSDL_LOCATION, new QName("tns:fare", "fare"));
    }

    /**
     * 
     * @return
     *     returns FarePortType
     */
    @WebEndpoint(name = "farePort")
    public FarePortType getFarePort() {
        return super.getPort(new QName("tns:fare", "farePort"), FarePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FarePortType
     */
    @WebEndpoint(name = "farePort")
    public FarePortType getFarePort(WebServiceFeature... features) {
        return super.getPort(new QName("tns:fare", "farePort"), FarePortType.class, features);
    }

}
